format:
  html:
    theme: cosmo
    df-print: paged
    fig-width: 8
    fig-height: 6
    subtitle: "Bigger Data, Easier Workflows"
    author: "Nic Crane, Jonathan Keane, and Neal Richardson"
    reader-mode: true
    repo-branch: main
    repo-actions: [source, issue]
    page-footer:
      left: |
        Scaling Up With R and Arrow was written by Nic Crane, Jonathan Keane,
        and Neal Richardson.
      right: |
        This book was built with <a href="https://quarto.org/">Quarto</a>.
