project:
  type: book
  output-dir: _book
  resources: 
    - CNAME

book:
  # we may need to comment the title out when rendering final version to pdf
  # but it breaks the chapter titles in sidebar in the html if we move it to that section
  title: "Scaling Up With R and Arrow"
  chapters:
    - index.qmd
    - foreword.qmd
    - intro.qmd
    - getting_started.qmd
    - data_manipulation.qmd
    - files_and_formats.qmd
    - datasets.qmd
    - cloud.qmd
    - advanced_topics.qmd
    - processes.qmd
    - references.qmd
  appendices:
  - appendix.qmd
  google-analytics: 
    tracking-id: "G-4JT42QR6DV"
  site-url: https://arrowrbook.com/
  repo-url: https://github.com/arrowrbook/book/

bibliography: references.bib

profile:
  group: 
    - [website, pdf]

editor: source

execute:
  freeze: auto
