project:
  type: book
  output-dir: _book

book:
  chapters:
    - index.qmd
    - foreword.qmd
    - intro.qmd
    - getting_started.qmd
    - data_manipulation.qmd
    - files_and_formats.qmd
    - datasets.qmd
    - cloud.qmd
    - advanced_topics.qmd
    - processes.qmd
    - references.qmd
  appendices:
  - appendix.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
    fig-width: 8
    fig-height: 6
    title: "Scaling Up With R and Arrow"
    subtitle: "Bigger Data, Easier Workflows"
    author: "Nic Crane, Jonathan Keane, and Neal Richardson"
    reader-mode: true
    google-analytics: "G-4JT42QR6DV"
    page-footer:
      left: |
        Scaling Up With R and Arrow was written by Nic Crane, Jonathan Keane,
        and Neal Richardson.
      right: |
        This book was built with <a href="https://quarto.org/">Quarto</a>.
  pdf:
    toc: false
    toc-title: "Contents"
    keep-tex: true
    cite-method: natbib
    biblio-style: apalike
    documentclass: krantz
    classoption: [krantz2]
    fig-width: 6
    # fig-height: 9
    # format-resources:
    #   - latex/krantz.cls
    hyperrefoptions: "bookmarks=false"
    links-as-notes: true
    colorlinks: false
    # For breaking lines in output
    knitr:
      opts_chunk:
        R.options:
          width: 64
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \frontmatter
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          % Note: setting commandchars=\\\{\} here will cause an error 
        }
    # highlight-style: grayscale-custom.theme
    # include-in-header: latex/preamble.tex
    # include-before-body: latex/before_body.tex
    # include-after-body: latex/after_body.tex

editor: source

execute:
  freeze: auto
