on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

name: Render with the subset data

permissions:
  contents: write
  pull-requests: write

jobs:
  render:
    runs-on: 'ubuntu-latest'
    concurrency:
      group: render-subset-data-${{ github.event.number }}
    name: Render the book using the small dataset
    steps:
      - uses: actions/checkout@v4

      - name: Fetch smol data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin CI_data:CI_data
          git checkout --no-overlay CI_data -- PUMS_smol

      - name: Link smol data
        run: ln -s PUMS_smol data

      - name: Cache data
        uses: actions/cache@v4
        with:
          path: data
          key: data-${{ hashFiles('PUMS_smol/*') }}
          restore-keys: data-

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: 'desc'

      - name: Setup PyArrow
        run: |
          Rscript -e "library(reticulate); virtualenv_create('pyarrow-env'); arrow::install_pyarrow('pyarrow-env'); py_install('pandas', 'pyarrow-env')"

      - name: Render Quarto Project
        env:
          PUMS_LOC: ./data
          QUARTO_PROFILE: rerender
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy to GH pages preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _book
